### ISSUE TITLE
TestCase querying issue

### ISSUE THREAD

**Issue by j-barata** [OSLC/lyo-samples#114]
Hi,
Based on the `ETMSample`, I wrote a query that should retrieve all the test cases of a given project area.

The result of this query is always an empty array, although there is actually 3 test cases in this project area.

Did I missed something ?

>String catalogUrl = new RootServicesHelper(`<My QM URL>`, OSLCConstants.OSLC_QM_V2, client).getCatalogUrl();
>String serviceProviderUrl = client.lookupServiceProviderUrl(catalogUrl, `<My QM project area>`);
>String queryCapability = client.lookupQueryCapability(serviceProviderUrl, OSLCConstants.OSLC_QM_V2, OSLCConstants.QM_TEST_CASE_QUERY);
>OslcQueryParameters queryParams = new OslcQueryParameters();
>queryParams.setPrefix("rdf=&lt;http://www.w3.org/1999/02/22-rdf-syntax-ns#&gt;");
>queryParams.setWhere("rdf:type=&lt;http://open-services.net/ns/qm#TestCase&gt;");
>OslcQuery query = new OslcQuery(client, queryCapability, -1, queryParams);
>OslcQueryResult result = query.submit();
>Assertions.assertNotNull(result);
>Assertions.assertEquals(3, result.getMembersUrls().length);

**Comment by j-barata** [comment]
Sorry, I didn't mentionned that the Lyo oslc-client version being used is the 4.0.0.

I also created a post on jazz.net (https://jazz.net/forum/questions/277030/testcase-querying-issue)

Thanks

**Comment by berezovskyi** [comment]
@j-barata I have no working experience with OSLC Query specifics on Jazz tools. I will close this ticket for now but if you find that Lyo caused the query to be prepared incorrectly, please feel free to reopen the ticket. Also, if you find a mistake in your code, we will be happy to update the samples.

**Comment by jadelkhoury** [comment]
I will try to answer on your post on Jazz form. 
I also suggest you post to Lyo community on https://forum.open-services.net/.
Otherewise agree that we open this issue here once we know there is a bug for Lyo to solve.
