### ISSUE TITLE
lyo-samples are not working with the latest oslc4j client library

### ISSUE THREAD

**Issue by maxler05** [OSLC/lyo-samples#36]
Hi, 

today I tried to run the examples with the lyo 4.0.0 dependencies - a few days ago they were working.

But with the latest patches of the oslc4j-client-4.0.0-SNAPSHOT.jar library the samples will not work anymore.
I had a look to the library itself, it doesn't contain the different resource classes (like ChangeRequest, Requirment, ...) anymore

Could someone check this please - or does someone has an idea?

Best regards
STeve

**Comment by berezovskyi** [comment]
Hi,

Right now you can update the version from 4.0.0-SNAPSHOT to 4.0.0.M2.

The long term solution is to switch from oslc4j-client:4.0.0-SNAPSHOT to oslc-client:4.0.0-SNAPSHOT because that's what will be released in Lyo 4.0.

**Comment by berezovskyi** [comment]
Just pushed https://github.com/OSLC/lyo-samples/commit/989405fece86bd504d8e7d93ac313bce259636d7 to master, please check

**Comment by berezovskyi** [comment]
Closing as fixed and #37 is opened as a follow-up
