### ISSUE TITLE
Update  oslc4j-client-samples to use new 4.0.0 client

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/lyo-samples#38]

**Comment by berezovskyi** [comment]
The code in question calls a method that is no longer in oslc-client:

```java
// IBM jazz-apps use JEE Form based authentication
clientBuilder.register(new JEEFormAuthenticator(webContextUrl, userId, password));

//STEP 3: Create a new OslcClient
OslcClient client = new OslcClient(clientBuilder);

//STEP 4: Get the URL of the OSLC ChangeManagement service from the rootservices document
String catalogUrl = client.getCatalogUrl(webContextUrl, OSLCConstants.OSLC_RM_V2);
```

@jadelkhoury @jamsden where is the `getCatalogUrl` method in the new client? I don't recall removing it.

**Comment by berezovskyi** [comment]
oslc4j-client-samples/src/main/java/org/eclipse/lyo/oslc4j/client/samples/ERMSample.java is the file in question

**Comment by jamsden** [comment]
I thought all those methods were moved into OslcClient, but I see they are in RootServicesHelper - which I thought I removed. I wanted all the discovery in OslcClient since that's where its mostly needed before any of the CURD REST services can be used.

**Comment by jamsden** [comment]
I found this in my notes:

### Add rootservices parsing to OslcClient

This is needed to interact with any of the jazz-apps, and is a useful approach to discovering discovery that may be incorporated into OSLC standards

- [x] Move JazzRootServicesHelper methods for rootservices into a subclass of OslcClient so its handled the same as OslcClient handles discovery. - [Add Jazz rootservices support to oslc4j-client OslcClient](https://github.com/eclipse/lyo.client/issues/25)

**Comment by jadelkhoury** [comment]
We already have JazzRootServicesHelper for the new client. See this for an example of how I use it. It was removed when we first moved to Jax-rs2.0. But then I migrated it, because I felt it was very useful.
https://github.com/OSLC/lyo-samples/blob/87e84fa59c7bc14ab270739b19c2934971c6e5a6/client-oauth-discovery-dui/src/main/java/org/eclipse/lyo/oslc4j/client/samples/DiscoveryServices.java#L213

@berezovskyi RootServiceHelper does have a getCatalogUrl(), but not sure if that is exactly what you are after?

**Comment by jamsden** [comment]
I really dislike these "helper" classes - they're generally a sign of poor design, and add clutter and overhead to OslcClient users. There were also issues with dependencies, that's why I eliminated the helper and moved the getCatalogURI method into the client. This an method that can be implemented many ways, so its not necessarily that coupled to jazz.net root services. And root services is so fundamental to access to jazz.net apps that it is useful for Lyo Client to have direct support in order to improve its relevance.

**Comment by berezovskyi** [comment]
> We already have JazzRootServicesHelper for the new client

Thanks @jadelkhoury, that's precisely what I was looking for and how the code shall be changed. Also, should this bit of info go into https://github.com/eclipse/lyo/issues/15?

> And root services is so fundamental to access to jazz.net apps that it is useful for Lyo Client to have direct support in order to improve its relevance.

I am going to quote you on this in the OP meeting next time I suggest to incorp root services spec into OSLC Core discovery :D

> I really dislike these "helper" classes - they're generally a sign of poor design, and add clutter and overhead to OslcClient users.

Yes agreed. But also this is a bit orthogonal to the authenticated client itself. Maybe a factory method would be nice, e.g.

```
IOslcClient client = OslcClients.fromRootServices(rootservicesUri, login, password);
IOslcClient client = OslcClients.fromRootServices(rootservicesUri, bearertoken);
IOslcClient client = OslcClients.fromWellKnownRootServices(bearertoken);
```

**Comment by jamsden** [comment]
I'd say keep it simple. All the other discovery methods are already in OslcClients, put the root one there too. I think client construction is already dealing with HTTP, SSL and authentication concerns. Adding a factory for root services seems unnecessary to me.

**Comment by jadelkhoury** [comment]
Keep it simple for me meant that I take exactly what was working for the old client and do minimal changes. That’s what I did. And I don’t think we need to change until it breaks.

**Comment by berezovskyi** [comment]
> I think client construction is already dealing with HTTP, SSL and authentication concerns. Adding a factory for root services seems unnecessary to me.

The reason is that root services doc may contain some of that info!

> I don’t think we need to change until it breaks.

Yes, let's do that till we get a use-case where we need to get auth config from the doc.

**Comment by jamsden** [comment]
It's already broken. The ERM test that I had working no longer works.

**Comment by berezovskyi** [comment]
Okay let’s check but if the implementation will be the same for every implementation of the client interface, I don’t want to duplicate this code.

**Comment by berezovskyi** [comment]
Fixed in https://github.com/OSLC/lyo-samples/commit/af2c54d71e187290f08129619ede7ae4894ef204
